import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: "800",
});

export const metadata: Metadata = {
  title: "angel's",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        id="root"
        className={`${nunito.className} antialiased bg-mybeige overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
